#!/usr/bin/env python3
"""Build the TKDE evidence inventory without training or mutating evidence.

The script reads only canonical locks, imported indexes, prediction manifests,
and validated saved-output analysis families.  It groups seed-level records
into claimable experimental cells and keeps blocked and diagnostic rows
explicit.  Output order is deterministic.
"""

from __future__ import annotations

import csv
import itertools
import json
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "results" / "tkde_rebuild"

FIELDS = [
    "evidence_id",
    "family",
    "dataset",
    "dataset_variant",
    "data_status",
    "prediction_unit",
    "class_definition_and_mapping",
    "temporal_range_or_window",
    "graph_construction",
    "graph_visibility",
    "protocol",
    "model_or_configuration",
    "seed_set",
    "n_seeds",
    "metrics",
    "provenance_level",
    "result_source",
    "prediction_export",
    "prediction_manifest",
    "statistical_pairing_key",
    "hardware_or_resource_envelope",
    "validation_status",
    "validation_source",
    "evidence_lock_status",
    "evidence_lock",
    "claim_gate_status",
    "claim_gate",
    "eligibility",
    "notes",
]

LABELS = {
    "elliptic": "raw licit->2, illicit->1, unknown->0; unknown excluded; positive=illicit (1)",
    "dgraphfin": "raw normal 0->licit 2, fraud 1->fraud 1, background 2/3->unknown 0; unknown excluded; positive=fraud (1)",
    "ibm_aml": "transaction is_laundering in {0,1}; positive=laundering (1)",
}

WINDOWS = {
    "elliptic": "49 time steps; train t1-30, validation t31-34, test t35-49",
    "dgraphfin": "20 incident-edge timestamp buckets; train t1-14, validation t15-16, test t17-20",
    "ibm_aml:late_window_holdout": "chronological 60% train / 20% validation / 20% test",
    "ibm_aml:early_to_late_transfer": "chronological 50% train / 20% validation / 30% test",
}

DATA_STATUS = {
    "elliptic": "real pseudonymized Bitcoin transaction graph",
    "dgraphfin": "real anonymized financial user graph",
    "ibm_aml": "synthetic financial transactions generated by IBM AML-Data",
}

RB09_METRICS = "F1; precision; recall; AUROC; AUPRC; Precision/Recall@100,@500,@1000,@1%; runtime"
IBM_METRICS = "F1@0.5; precision@0.5; recall@0.5; balanced accuracy; AUROC; AUPRC; runtime; saved scores"


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def rel(path: Path | str) -> str:
    path = Path(path)
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def seeds_text(values: Iterable[int | str]) -> tuple[str, int]:
    seeds = sorted({int(value) for value in values})
    if not seeds:
        return "none", 0
    if seeds == list(range(seeds[0], seeds[-1] + 1)):
        return f"{seeds[0]}-{seeds[-1]}", len(seeds)
    return ";".join(str(seed) for seed in seeds), len(seeds)


def base_row(**updates: Any) -> dict[str, Any]:
    row: dict[str, Any] = {field: "" for field in FIELDS}
    row.update(updates)
    return row


def graph_visibility(protocol: str) -> str:
    return {
        "strict_inductive": "test nodes and incident test edges withheld from training graph; test-time graph restricted by strict contract",
        "inductive_isolated": "chronological split with isolated split-specific evaluation subgraph",
        "transductive": "full graph structure visible while test labels remain hidden",
        "late_window_holdout": "node history features use the first 60% of transactions (this protocol's training interval); test transaction labels unavailable",
        "early_to_late_transfer": "classifier labels use the first 50%, while the shared label-free node-history map uses the first 60% (including covariates from the first half of this protocol's validation interval); test labels unavailable",
    }.get(protocol, "defined by source experiment contract")


def add_rb09(rows: list[dict[str, Any]]) -> None:
    path = ROOT / "results" / "runs_rb09v3" / "runs.csv"
    records = read_csv(path)
    pred_manifest = ROOT / "results" / "runs_rb09v3" / "predictions_manifest.json"
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = defaultdict(list)
    for record in records:
        grouped[(record["dataset"], record["protocol"], record["model"])].append(record)
    for (dataset, protocol, model), group in sorted(grouped.items()):
        seed_text, n_seeds = seeds_text(record["seed"] for record in group)
        split = group[0]["split_name"]
        rows.append(
            base_row(
                evidence_id=f"RB09::{dataset}::{protocol}::{model}",
                family="core strict/isolated/transductive benchmark",
                dataset=dataset,
                dataset_variant="canonical",
                data_status=DATA_STATUS[dataset],
                prediction_unit="account/node",
                class_definition_and_mapping=LABELS[dataset],
                temporal_range_or_window=f"{WINDOWS[dataset]}; split id {split}",
                graph_construction="published account/node graph; node features scaled on training mask only",
                graph_visibility=graph_visibility(protocol),
                protocol=protocol,
                model_or_configuration={"sage": "GraphSAGE"}.get(model, model.upper() if model in {"mlp", "gcn"} else model),
                seed_set=seed_text,
                n_seeds=n_seeds,
                metrics=RB09_METRICS,
                provenance_level="validated saved results",
                result_source=rel(path),
                prediction_export="available by manifest reference",
                prediction_manifest=rel(pred_manifest),
                statistical_pairing_key=f"dataset={dataset}|model={model}|seed|protocol",
                hardware_or_resource_envelope="CUDA benchmark artifacts; exact command and runtime recorded per row",
                validation_status="PASS artifact family: 180 results and 180 prediction references",
                validation_source="results/runs_rb09v3/ARTIFACT_FAMILY.json",
                evidence_lock_status="frozen artifact family",
                evidence_lock="results/runs_rb09v3/ARTIFACT_FAMILY.json",
                claim_gate_status="eligible within exact dataset/model/protocol scope",
                claim_gate="results/runs_rb09v3/ARTIFACT_FAMILY.json",
                eligibility="main-paper eligible",
                notes="MLP is the graph-visibility negative control; do not infer graph effects from its identical score rows alone without paired analysis.",
            )
        )


def add_rb11(rows: list[dict[str, Any]]) -> None:
    base = ROOT / "results" / "runs_rb11_sage_family"
    records = read_csv(base / "runs.csv")
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = defaultdict(list)
    for record in records:
        grouped[(record["dataset"], record["protocol"], record["model"])].append(record)
    for (dataset, protocol, model), group in sorted(grouped.items()):
        seed_text, n_seeds = seeds_text(record["seed"] for record in group)
        rows.append(
            base_row(
                evidence_id=f"RB11::{dataset}::{protocol}::{model}",
                family="GraphSAGE-family architecture diagnostic",
                dataset=dataset,
                dataset_variant="canonical",
                data_status=DATA_STATUS[dataset],
                prediction_unit="account/node",
                class_definition_and_mapping=LABELS[dataset],
                temporal_range_or_window=WINDOWS[dataset],
                graph_construction="published account/node graph",
                graph_visibility=graph_visibility(protocol),
                protocol=protocol,
                model_or_configuration={"sage": "GraphSAGE mean", "sage_maxpool": "GraphSAGE max-pool", "mlp": "MLP"}.get(model, model),
                seed_set=seed_text,
                n_seeds=n_seeds,
                metrics=RB09_METRICS,
                provenance_level="saved diagnostic outputs",
                result_source=rel(base / "runs.csv"),
                prediction_export="available locally",
                prediction_manifest=rel(base / "manifest.json"),
                statistical_pairing_key=f"dataset={dataset}|model={model}|seed|protocol",
                hardware_or_resource_envelope="original saved-output diagnostic; runtime recorded per row",
                validation_status="aggregate and analysis manifests present",
                validation_source=rel(base / "analysis_manifest.json"),
                evidence_lock_status="not a later imported full10 lock",
                evidence_lock=rel(base / "aggregate_manifest.json"),
                claim_gate_status="bounded diagnostic only",
                claim_gate=rel(base / "analysis_manifest.json"),
                eligibility="diagnostic-only",
                notes="Five-seed Elliptic diagnostic; the requested DGraphFin RB11b directory is absent and RB18 remains blocked.",
            )
        )


def add_v22(rows: list[dict[str, Any]]) -> None:
    lock_path = ROOT / "kaggle_workspace" / "manifests" / "V22_FINAL_GPU_EVIDENCE_LOCK.json"
    lock = load_json(lock_path)
    full10_root = ROOT / "kaggle_workspace" / "imported_outputs" / "v22_full10"
    for lane in lock["lanes"]:
        dataset = lane["dataset"]
        if not lane.get("final_claim_eligibility"):
            rows.append(
                base_row(
                    evidence_id=f"V22::{lane['family']}::{dataset}::BLOCKED",
                    family="loss/control/architecture extension",
                    dataset=dataset,
                    dataset_variant="canonical",
                    data_status=DATA_STATUS[dataset],
                    prediction_unit="account/node",
                    class_definition_and_mapping=LABELS[dataset],
                    temporal_range_or_window=WINDOWS[dataset],
                    graph_construction="published account/node graph",
                    graph_visibility="not measured",
                    protocol="not measured",
                    model_or_configuration="GAT/GIN extra-architecture lane",
                    seed_set="none",
                    n_seeds=0,
                    metrics="none",
                    provenance_level="resource status only",
                    result_source=rel(lock_path),
                    prediction_export="absent",
                    prediction_manifest="none",
                    statistical_pairing_key="none",
                    hardware_or_resource_envelope="T4; fixed DGraphFin extra-architecture lane stopped by CUDA OOM",
                    validation_status=lane["status"],
                    validation_source="kaggle_workspace/reports/V22_FINAL_AUDIT.md",
                    evidence_lock_status=lane["status"],
                    evidence_lock=rel(lock_path),
                    claim_gate_status="resource-blocked; no predictive ordering",
                    claim_gate="kaggle_workspace/reports/V22_FINAL_GPU_EVIDENCE_LOCK.md",
                    eligibility="resource-blocked",
                    notes=f"Expected {lane['expected_json']} results and predictions; imported 0. Missing seeds 1-10.",
                )
            )
            continue
        lane_dir = full10_root / lane["lane_id"]
        source = lane_dir / "RESULTS_FULL10.jsonl"
        grouped: dict[tuple[str, str, str, str], list[dict[str, Any]]] = defaultdict(list)
        with source.open("r", encoding="utf-8") as handle:
            for line in handle:
                record = json.loads(line)
                grouped[(record["protocol"], record["model"], record.get("loss", ""), record.get("control", ""))].append(record)
        for (protocol, model, loss, control), group in sorted(grouped.items()):
            seed_text, n_seeds = seeds_text(record["seed"] for record in group)
            condition = control or loss or "default"
            rows.append(
                base_row(
                    evidence_id=f"V22::{lane['family']}::{dataset}::{protocol}::{model}::{condition}",
                    family="loss/control/architecture extension",
                    dataset=dataset,
                    dataset_variant="canonical",
                    data_status=DATA_STATUS[dataset],
                    prediction_unit="account/node",
                    class_definition_and_mapping=LABELS[dataset],
                    temporal_range_or_window=WINDOWS[dataset],
                    graph_construction="published account/node graph" + (f"; control={control}" if control else ""),
                    graph_visibility=graph_visibility(protocol),
                    protocol=protocol,
                    model_or_configuration=f"{model}; loss={loss or 'weighted_bce'}" + (f"; control={control}" if control else ""),
                    seed_set=seed_text,
                    n_seeds=n_seeds,
                    metrics=RB09_METRICS,
                    provenance_level="canonical imported full10 merged evidence",
                    result_source=rel(source),
                    prediction_export="available and schema-valid",
                    prediction_manifest=rel(lane_dir / "PREDICTIONS_FULL10_INDEX_V22.json"),
                    statistical_pairing_key=f"dataset={dataset}|model={model}|seed|protocol|condition={condition}",
                    hardware_or_resource_envelope="dual/single Tesla T4 Kaggle lanes; compatibility aliases recorded in lock",
                    validation_status=lane["status"],
                    validation_source=rel(lane_dir / "FULL10_MERGE_VALIDATION_V22.json"),
                    evidence_lock_status=lane["status"],
                    evidence_lock=rel(lock_path),
                    claim_gate_status="eligible within exact loss/control/architecture cell",
                    claim_gate="kaggle_workspace/reports/V22_FINAL_GPU_EVIDENCE_LOCK.md",
                    eligibility="supplement-only",
                    notes="Version aliases are compatibility mappings in the canonical lock, not new experiments.",
                )
            )
    excluded_counts = {
        "RB28_ELLIPTIC_LOSS_ROBUSTNESS_SEEDS_1_2_DUALGPU_V22": "1 result and 1 prediction; seed 2 missing; sole cell is DGraphFin GCN despite directory name",
        "RB28_ELLIPTIC_LOSS_ROBUSTNESS_SMOKE_2SEED_V20": "36 results and 36 predictions; smoke/noncomparable source and failed return-code gate",
        "RB30_ELLIPTIC_EXTRA_ARCH_SEEDS_1_2_DUALGPU_V22": "1 result and 1 prediction; seed 2 missing; duplicate/conflicting merge metadata; actual cell is DGraphFin GCN",
    }
    for item in sorted(
        (entry for entry in lock.get("rows", []) if not entry.get("final_claim_eligibility")),
        key=lambda entry: entry["run_id"],
    ):
        run_id = item["run_id"]
        validation = ROOT / "kaggle_workspace" / "imported_outputs" / "v22" / run_id / "IMPORT_VALIDATION_V22.json"
        rows.append(
            base_row(
                evidence_id=f"V22::excluded::{run_id}",
                family="excluded V22 import",
                dataset="not inferable from directory name",
                dataset_variant="partial/noncomparable",
                data_status="excluded imported artifact",
                prediction_unit="account/node",
                class_definition_and_mapping="not promoted because integrity/completeness gate failed",
                temporal_range_or_window="partial source only",
                graph_construction="not promoted",
                graph_visibility="not promoted",
                protocol="not promoted",
                model_or_configuration="not promoted",
                seed_set=";".join(str(seed) for seed in item.get("seed_coverage", [])) or "none",
                n_seeds=len(item.get("seed_coverage", [])),
                metrics="present in raw files but excluded from all aggregates",
                provenance_level="failed import candidate",
                result_source=";".join(item.get("source_artifact_paths", [])),
                prediction_export="partial/noncomparable and excluded",
                prediction_manifest=rel(validation),
                statistical_pairing_key="none",
                hardware_or_resource_envelope="not eligible for hardware or performance claims",
                validation_status=item["imported_status"],
                validation_source=rel(validation),
                evidence_lock_status=item["imported_status"],
                evidence_lock=rel(lock_path),
                claim_gate_status="excluded: integrity/completeness failed",
                claim_gate=rel(lock_path),
                eligibility="excluded",
                notes=excluded_counts.get(run_id, "Failed V22 import candidate; directory names are not evidence."),
            )
        )


def add_v24(rows: list[dict[str, Any]]) -> None:
    lock_path = ROOT / "results" / "v24_imported" / "V24_IMPORTED_EVIDENCE_LOCK.json"
    lock = load_json(lock_path)
    indexes = sorted((ROOT / "results" / "v24_imported").glob("*/RESULT_INDEX.csv"))
    grouped: dict[tuple[str, str, str, str, str, int, int], list[dict[str, str]]] = defaultdict(list)
    source_paths: dict[tuple[str, str, str, str, str, int, int], set[str]] = defaultdict(set)
    for index in indexes:
        for record in read_csv(index):
            key = (
                record["dataset"],
                record["protocol"],
                record["model"],
                record["stress_config"],
                record["control_mode"],
                int(record["hidden_channels"]),
                int(record["num_layers"]),
            )
            grouped[key].append(record)
            source_paths[key].add(rel(index))
    lane_by_family_dataset = {}
    for lane in lock["lanes"]:
        family = "RB44" if "RB44" in lane["lane_id"] else "RB45" if "RB45" in lane["lane_id"] else "RB41"
        lane_by_family_dataset[(family, lane["datasets"][0])] = lane
    for key, group in sorted(grouped.items()):
        dataset, protocol, model, stress, control, hidden, layers = key
        family = group[0]["stress_family"]
        lane = lane_by_family_dataset[(family, dataset)]
        seed_text, n_seeds = seeds_text(record["seed"] for record in group)
        eligibility = "supplement-only" if family in {"RB41", "RB44"} else "diagnostic-only"
        notes = "Temporal stress label is metadata only in the V24 runner: it is not passed to the benchmark harness. Performance metrics duplicate exactly across all three labels. Do not compare, pool, or count those labels as distinct conditions; retain one deduplicated strict/isolated rerun grid at most."
        if family == "RB45":
            notes = "Memory-reduced GAT h32/l1 is exploratory and not comparable to the blocked fixed h64/l2 lane."
        rows.append(
            base_row(
                evidence_id=f"V24::{family}::{dataset}::{stress}::{protocol}::{model}",
                family="temporal-shift/perturbation stress",
                dataset=dataset,
                dataset_variant="canonical",
                data_status=DATA_STATUS[dataset],
                prediction_unit="account/node",
                class_definition_and_mapping=LABELS[dataset],
                temporal_range_or_window=f"{WINDOWS[dataset]}; stress={stress}",
                graph_construction="published account/node graph" + (f"; control={control}" if control != "none" else ""),
                graph_visibility=graph_visibility(protocol),
                protocol=protocol,
                model_or_configuration=f"{model}; hidden={hidden}; layers={layers}",
                seed_set=seed_text,
                n_seeds=n_seeds,
                metrics="F1; precision; recall; AUROC; AUPRC; Precision/Recall@1%; runtime",
                provenance_level="canonical imported package index",
                result_source=";".join(sorted(source_paths[key])),
                prediction_export="available",
                prediction_manifest=lane["prediction_index_csv"],
                statistical_pairing_key=f"dataset={dataset}|stress={stress}|model={model}|seed|protocol",
                hardware_or_resource_envelope="validated Kaggle execution; V24 environment records two Tesla T4 devices",
                validation_status=lane["status"],
                validation_source=";".join(lane["split_manifest_paths"]),
                evidence_lock_status=lock["status"],
                evidence_lock=rel(lock_path),
                claim_gate_status=(
                    "artifact lock PASS, but temporal-stress construct invalid; only deduplicated strict/isolated rerun is scientifically usable"
                    if family == "RB41"
                    else f"eligible as {lane['claim_scope']}"
                ),
                claim_gate=rel(lock_path),
                eligibility=eligibility,
                notes=notes,
            )
        )
    for blocked in lock.get("fixed_blocked_lanes", []):
        rows.append(
            base_row(
                evidence_id=f"V24::{blocked['lane_id']}::BLOCKED",
                family="temporal-shift/architecture stress",
                dataset="dgraphfin",
                dataset_variant="canonical",
                data_status=DATA_STATUS["dgraphfin"],
                prediction_unit="account/node",
                class_definition_and_mapping=LABELS["dgraphfin"],
                temporal_range_or_window=WINDOWS["dgraphfin"],
                graph_construction="published DGraphFin graph",
                graph_visibility="not measured",
                protocol="not measured",
                model_or_configuration="GAT hidden=64 layers=2",
                seed_set="none",
                n_seeds=0,
                metrics="none",
                provenance_level="resource status only",
                result_source=rel(lock_path),
                prediction_export="absent",
                prediction_manifest="none",
                statistical_pairing_key="none",
                hardware_or_resource_envelope="Tesla T4; CUDA OOM",
                validation_status=blocked["status"],
                validation_source=rel(lock_path),
                evidence_lock_status=blocked["status"],
                evidence_lock=rel(lock_path),
                claim_gate_status="resource-blocked; no predictive ordering",
                claim_gate=rel(lock_path),
                eligibility="resource-blocked",
                notes=blocked["reason"],
            )
        )


def ibm_scientific_config(config: str) -> tuple[str, str]:
    mapping = {
        "logistic_regression_edge_features": ("logistic regression on transaction features", "edge feature table; no message passing"),
        "hist_gradient_boosting_edge_features": ("histogram gradient boosting on transaction features", "edge feature table; no message passing"),
        "graphsage_edge_minibatch_h32": ("one-hop GraphSAGE-derived edge classifier h32", "account transaction network with training-history neighborhood summaries"),
        "edge_aware_graphsage_h64": ("edge-aware one-hop GraphSAGE-derived edge classifier h64", "account transaction network with original transaction edge features"),
        "edge_aware_graphsage_h64_no_edge_features": ("edge-aware GraphSAGE h64, NoEdge", "original graph structure; zeroed transaction features"),
        "edge_aware_graphsage_h64_shuffled_edge_features": ("edge-aware GraphSAGE h64, ShuffledEdge", "original graph; edge features shuffled within temporal masks"),
        "edge_aware_graphsage_h64_degree_only": ("edge-aware GraphSAGE h64, DegreeOnly", "original graph; edge attributes replaced by endpoint-degree features"),
        "degree_capped_bipartite": ("edge-aware GraphSAGE h64, DegreeCap", "training structure degree-capped at q=0.995"),
        "recent_window_only_graph": ("edge-aware GraphSAGE h64, RecentWindow", "most recent 50% of training edges form message-passing structure"),
        "account_account_sender_receiver": ("edge-aware GraphSAGE h64, sender-receiver construction", "sender-to-receiver account projection of transaction edges"),
        "gine_light_h64": ("one-layer GINE edge classifier h64", "account transaction network with original edge features"),
    }
    return mapping.get(config, (config, "account transaction network"))


def add_ibm(rows: list[dict[str, Any]]) -> None:
    sources = {
        "V26": sorted((ROOT / "results" / "v26_imported" / "ibm_aml").glob("**/json/*.json")),
        "V27": sorted((ROOT / "results" / "v27_imported" / "imported_json").glob("*.json")),
        "V28": sorted((ROOT / "results" / "v28_imported" / "imported_json").glob("*.json")),
    }
    locks = {
        "V26": ROOT / "results" / "v26_imported" / "V26_IMPORTED_EVIDENCE_LOCK.json",
        "V27": ROOT / "results" / "v27_imported" / "V27_STRONGER_GRAPH_EVIDENCE_LOCK.json",
        "V28": ROOT / "results" / "v28_imported" / "V28_ALL_RUNS_EVIDENCE_LOCK.json",
    }
    gates = {
        "V26": ROOT / "results" / "v26_imported" / "V26_CLAIM_GATE_REPORT.json",
        "V27": ROOT / "results" / "v27_imported" / "V27_STRONGER_GRAPH_CLAIM_GATE_REPORT.json",
        "V28": ROOT / "results" / "v28_imported" / "V28_ALL_RUNS_CLAIM_GATE_REPORT.json",
    }
    validations = {
        "V26": ROOT / "results" / "v26_imported" / "V26_IBM_AML_VALIDATION_REPORT.json",
        "V27": ROOT / "results" / "v27_imported" / "V27_STRONGER_GRAPH_VALIDATION_REPORT.json",
        "V28": ROOT / "results" / "v28_imported" / "V28_ALL_RUNS_VALIDATION_REPORT.json",
    }
    pred_manifests = {
        "V26": ROOT / "results" / "v26_imported" / "V26_IBM_AML_REVIEW_BUDGET_MANIFEST.json",
        "V27": ROOT / "results" / "v27_imported" / "V27_PREDICTION_EXPORT_MANIFEST.csv",
        "V28": ROOT / "results" / "v28_imported" / "V28_PREDICTION_EXPORT_MANIFEST.csv",
    }
    lock_payloads = {version: load_json(path) for version, path in locks.items()}
    for version, files in sources.items():
        grouped: dict[tuple[str, str, str], list[tuple[Path, dict[str, Any]]]] = defaultdict(list)
        for path in files:
            payload = load_json(path)
            config = payload.get("v28_config") or payload["model"]
            grouped[(payload["variant"], payload["protocol"], config)].append((path, payload))
        for (variant, protocol, config), group in sorted(grouped.items()):
            seed_text, n_seeds = seeds_text(payload["seed"] for _, payload in group)
            sample = group[0][1]
            model_name, construction = ibm_scientific_config(config)
            graph_stats = sample["graph_stats"]
            backend_values = sorted({str(payload.get("actual_backend", "")) for _, payload in group})
            lock_status = lock_payloads[version]["status"]
            rows.append(
                base_row(
                    evidence_id=f"{version}::ibm_aml::{variant}::{protocol}::{config}",
                    family={"V26": "IBM AML baseline grid", "V27": "IBM AML stronger graph study", "V28": "IBM AML construction/feature ablation"}[version],
                    dataset="IBM AML-Data",
                    dataset_variant=variant,
                    data_status=DATA_STATUS["ibm_aml"],
                    prediction_unit="transaction/edge",
                    class_definition_and_mapping=LABELS["ibm_aml"],
                    temporal_range_or_window=WINDOWS[f"ibm_aml:{protocol}"],
                    graph_construction=f"{construction}; {graph_stats['num_accounts']} accounts; {graph_stats['num_transactions']} transactions; {graph_stats['edge_feature_dim']} edge features",
                    graph_visibility=graph_visibility(protocol),
                    protocol=protocol,
                    model_or_configuration=model_name,
                    seed_set=seed_text,
                    n_seeds=n_seeds,
                    metrics=IBM_METRICS,
                    provenance_level="canonical imported full10 evidence",
                    result_source=";".join(rel(path) for path, _ in group),
                    prediction_export="available for every seed/cell",
                    prediction_manifest=rel(pred_manifests[version]),
                    statistical_pairing_key=f"variant={variant}|protocol={protocol}|seed|configuration",
                    hardware_or_resource_envelope=f"single Tesla T4 environment; assigned cuda:0; actual backends={','.join(backend_values)}",
                    validation_status="PASS",
                    validation_source=rel(validations[version]),
                    evidence_lock_status=lock_status,
                    evidence_lock=rel(locks[version]),
                    claim_gate_status="eligible within exact variant/protocol/configuration scope",
                    claim_gate=rel(gates[version]),
                    eligibility="main-paper eligible",
                    notes="IBM AML-Data is synthetic. Threshold metrics use score >= 0.5. Compare GINE only on matched Small cells. The materialized node-history map is shared across protocols and is built from the first 60% of transactions; early-to-late therefore permits label-free covariates from 50-60%, which must be treated as part of its visibility contract.",
                )
            )
    v26_lock = lock_payloads["V26"]
    for item in v26_lock["v26_ibm_aml_variants"]:
        if item["status"] == "FULL10_PASS":
            continue
        rows.append(
            base_row(
                evidence_id=f"V26::ibm_aml::{item['variant']}::BLOCKED",
                family="IBM AML resource boundary",
                dataset="IBM AML-Data",
                dataset_variant=item["variant"],
                data_status=DATA_STATUS["ibm_aml"],
                prediction_unit="transaction/edge",
                class_definition_and_mapping=LABELS["ibm_aml"],
                temporal_range_or_window="not instantiated",
                graph_construction="official Large variant; graph not admitted by safe resource guard",
                graph_visibility="not measured",
                protocol="not measured",
                model_or_configuration="baseline grid not executed",
                seed_set="none",
                n_seeds=0,
                metrics="none",
                provenance_level="resource status only",
                result_source=rel(locks["V26"]),
                prediction_export="absent",
                prediction_manifest="none",
                statistical_pairing_key="none",
                hardware_or_resource_envelope="safe resource guard blocked official Large variant",
                validation_status=item["status"],
                validation_source=rel(validations["V26"]),
                evidence_lock_status=item["status"],
                evidence_lock=rel(locks["V26"]),
                claim_gate_status="resource-blocked; no predictive ordering",
                claim_gate=rel(gates["V26"]),
                eligibility="resource-blocked",
                notes="Large is a feasibility boundary, not an empirical performance result.",
            )
        )
    for blocked in lock_payloads["V28"].get("blocked_runs", []):
        rows.append(
            base_row(
                evidence_id=f"V28::ibm_aml::{blocked['variant']}::{blocked['config']}::BLOCKED",
                family="IBM AML construction/feature ablation",
                dataset="IBM AML-Data",
                dataset_variant=blocked["variant"],
                data_status=DATA_STATUS["ibm_aml"],
                prediction_unit="transaction/edge",
                class_definition_and_mapping=LABELS["ibm_aml"],
                temporal_range_or_window="both planned protocols; no result instantiated",
                graph_construction="account transaction network with original edge features",
                graph_visibility="not measured",
                protocol="late-window holdout and early-to-late transfer planned",
                model_or_configuration="one-layer GINE edge classifier h64",
                seed_set="none",
                n_seeds=0,
                metrics="none",
                provenance_level="resource status only",
                result_source=rel(locks["V28"]),
                prediction_export="absent",
                prediction_manifest="none",
                statistical_pairing_key="none",
                hardware_or_resource_envelope="single Tesla T4 (~14.56 GiB available); CUDA OOM requesting ~4.56 GiB",
                validation_status=blocked["status"],
                validation_source=rel(validations["V28"]),
                evidence_lock_status=blocked["status"],
                evidence_lock=rel(locks["V28"]),
                claim_gate_status="resource-blocked; no Medium GINE performance claim",
                claim_gate=rel(gates["V28"]),
                eligibility="resource-blocked",
                notes="Twenty planned outputs per variant (10 seeds x 2 protocols) have zero result and prediction files.",
            )
        )


def add_saved_output_families(rows: list[dict[str, Any]]) -> None:
    families = [
        (
            "RB15",
            "GraphSafe-TTA saved-output analysis",
            "results/runs_rb15_graphsafe_tta/graphsafe_tta_results.csv",
            "results/runs_rb15_graphsafe_tta/import_manifest.json",
            "results/runs_rb15_graphsafe_tta/validation_report.json",
            "1200 method/seed/cell rows plus 720 ablation rows; at least one decision-level Holm-corrected result in its exact tested scope",
        ),
        (
            "RB15b",
            "validation-selected conservative GraphSafe policy",
            "results/runs_rb15b_graphsafe_conservative_policy/conservative_policy_results.csv",
            "results/runs_rb15b_graphsafe_conservative_policy/import_manifest.json",
            "results/runs_rb15_graphsafe_tta/validation_report.json",
            "120 policy rows; selection uses validation reliability only",
        ),
        (
            "RB16",
            "GraphSafe best-branch strengthening",
            "results/runs_rb16_graphsafe_best_branch_strengthening/rb16_results.csv",
            "results/runs_rb16_graphsafe_best_branch_strengthening/import_manifest.json",
            "results/runs_rb16_graphsafe_best_branch_strengthening/validation_report.json",
            "2280 saved-output rows; apparent best-branch wins do not survive Holm correction in the summarized comparisons",
        ),
        (
            "RB17",
            "review-budget/worst-block/cost sensitivity",
            "results/runs_rb17_review_budget_worst_block/rb17_results.csv",
            "results/runs_rb17_review_budget_worst_block/import_manifest.json",
            "results/runs_rb17_review_budget_worst_block/validation_report.json",
            "2280 result rows and 9120 cost rows; costs reconstructed at saved thresholds, not reoptimized",
        ),
    ]
    for family, name, result, manifest, validation, note in families:
        rows.append(
            base_row(
                evidence_id=f"{family}::saved_prediction_analysis",
                family=name,
                dataset="Elliptic; DGraphFin",
                dataset_variant="canonical",
                data_status="real saved-prediction analyses",
                prediction_unit="account/node",
                class_definition_and_mapping="dataset-specific mappings above; positive=fraud/illicit",
                temporal_range_or_window="inherits locked RB09 prediction windows",
                graph_construction="feature-only and graph branches inherited from saved prediction families",
                graph_visibility="inherits strict/isolated/transductive source contracts",
                protocol="saved-output policy evaluation",
                model_or_configuration=name,
                seed_set="1-10",
                n_seeds=10,
                metrics="F1; Recall@1%; cost-sensitive risk; worst-block and average-block regret; reliability diagnostics",
                provenance_level="CPU-only derived analysis of saved predictions",
                result_source=result,
                prediction_export="source predictions referenced in import manifest",
                prediction_manifest=manifest,
                statistical_pairing_key="dataset|source protocol/model|seed|policy/comparator",
                hardware_or_resource_envelope="no new training; CPU-only derivation from saved outputs",
                validation_status="PASS",
                validation_source=validation,
                evidence_lock_status="inherits source prediction family; derived outputs validated",
                evidence_lock=manifest,
                claim_gate_status="bounded case-study/diagnostic scope",
                claim_gate=result.replace("results.csv", "statistical_tests.csv"),
                eligibility="supplement-only" if family in {"RB16", "RB17"} else "main case-study eligible",
                notes=note,
            )
        )
    rows.append(
        base_row(
            evidence_id="RB18::dgraphfin::sage_maxpool::BLOCKED",
            family="large-GPU GraphSAGE architecture rerun",
            dataset="dgraphfin",
            dataset_variant="canonical",
            data_status=DATA_STATUS["dgraphfin"],
            prediction_unit="account/node",
            class_definition_and_mapping=LABELS["dgraphfin"],
            temporal_range_or_window=WINDOWS["dgraphfin"],
            graph_construction="published DGraphFin graph",
            graph_visibility="strict/isolated planned; not measured",
            protocol="strict_inductive and inductive_isolated planned",
            model_or_configuration="GraphSAGE max-pool",
            seed_set="none",
            n_seeds=0,
            metrics="none",
            provenance_level="run preparation only",
            result_source="results/runs_rb18_large_gpu_rb11b/rb18_status.json",
            prediction_export="absent",
            prediction_manifest="none",
            statistical_pairing_key="none",
            hardware_or_resource_envelope="larger GPU required; no output imported",
            validation_status="BLOCKED_WAITING_FOR_GPU",
            validation_source="results/runs_rb18_large_gpu_rb11b/validation_report.json",
            evidence_lock_status="not locked as empirical evidence",
            evidence_lock="results/runs_rb18_large_gpu_rb11b/import_manifest.json",
            claim_gate_status="blocked; false to describe as completed",
            claim_gate="results/runs_rb18_large_gpu_rb11b/validation_report.json",
            eligibility="resource-blocked",
            notes="The separately requested results/runs_rb11b_dgraphfin_sage_family directory is absent.",
        )
    )


def add_governance_surfaces(rows: list[dict[str, Any]]) -> None:
    paths = [
        ("V29", "integrated benchmark summaries", "results/v29_integrated", "derived, not a new empirical family"),
        ("V30", "expected finalization layer", "results/v30_final", "directory absent"),
        ("V31", "public evaluator", "results/v31_public_evaluator", "evaluation tooling"),
        ("V32", "hidden-test contract", "results/v32_hidden_test", "governance/tooling"),
        ("V33", "dataset onboarding", "results/v33_dataset_onboarding", "documentation/contract"),
        ("V34", "model onboarding", "results/v34_model_onboarding", "documentation/contract"),
        ("V35", "resource stress audit", "results/v35_stress", "resource-governance derivative"),
        ("V36", "compute fairness", "results/v36_compute_fairness", "resource-governance derivative"),
        ("V37", "calibration/review-budget analysis", "results/v37_calibration", "CPU-only derivative"),
        ("V38", "cross-variant transfer summary", "results/v38_transfer", "derived aggregate"),
        ("V39", "release layer", "results/v39_release", "release/audit surface"),
    ]
    for version, name, path_text, note in paths:
        path = ROOT / path_text
        rows.append(
            base_row(
                evidence_id=f"{version}::governance_surface",
                family=name,
                dataset="inherits V26-V28/RB families" if path.exists() else "none",
                dataset_variant="not an independent experiment",
                data_status="derived/tooling" if path.exists() else "missing",
                prediction_unit="inherits sources" if path.exists() else "none",
                class_definition_and_mapping="inherits sources" if path.exists() else "none",
                temporal_range_or_window="inherits sources" if path.exists() else "none",
                graph_construction="inherits sources" if path.exists() else "none",
                graph_visibility="inherits sources" if path.exists() else "none",
                protocol="audit/tooling",
                model_or_configuration="not applicable",
                seed_set="inherits sources" if path.exists() else "none",
                n_seeds="",
                metrics="derived only" if path.exists() else "none",
                provenance_level="downstream audit/release surface" if path.exists() else "absent",
                result_source=path_text,
                prediction_export="not a new prediction family",
                prediction_manifest="inherits canonical inputs",
                statistical_pairing_key="inherits source analysis",
                hardware_or_resource_envelope="no new model training",
                validation_status="present" if path.exists() else "MISSING_DIRECTORY",
                validation_source=path_text,
                evidence_lock_status="does not supersede canonical empirical locks",
                evidence_lock="V26/V27/V28 and source-family locks",
                claim_gate_status="navigation/tooling only",
                claim_gate=path_text,
                eligibility="diagnostic-only" if path.exists() else "excluded",
                notes=note,
            )
        )


def markdown_table(rows: list[dict[str, Any]], fields: list[str]) -> str:
    def clean(value: Any) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ")
    lines = [
        "| " + " | ".join(fields) + " |",
        "| " + " | ".join("---" for _ in fields) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(clean(row[field]) for field in fields) + " |")
    return "\n".join(lines) + "\n"


def write_outputs(rows: list[dict[str, Any]]) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rows.sort(key=lambda row: row["evidence_id"])
    with (OUT / "EVIDENCE_INVENTORY.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    counts: dict[str, int] = defaultdict(int)
    for row in rows:
        counts[str(row["eligibility"])] += 1
    summary = "\n".join(f"- `{key}`: {counts[key]} rows" for key in sorted(counts))
    compact_fields = [
        "evidence_id",
        "dataset",
        "dataset_variant",
        "protocol",
        "model_or_configuration",
        "seed_set",
        "validation_status",
        "eligibility",
    ]
    text = f"""# TKDE Evidence Inventory

This inventory is generated from canonical locks, imported indexes, saved-prediction manifests, and validation reports. One row is one claimable experimental cell over a complete seed set, or one explicit blocked/diagnostic/governance cell. It does not treat filenames, dry runs, missing outputs, or blocked lanes as performance evidence.

Total rows: **{len(rows)}**.

{summary}

The canonical machine-readable version is `EVIDENCE_INVENTORY.csv`; the compact table below omits long provenance fields only for readability.

## Conflict resolutions

- V22 evidence is under `kaggle_workspace/`, not `results/v22*`; the canonical V22 lock is recorded there.
- The legacy `P100` token in one V26 lane identifier is an alias, not hardware evidence. Imported records show `cuda:0`, and the normalized execution environment is Tesla T4.
- V24's memory-reduced DGraphFin GAT h32/l1 diagnostic does not replace the fixed h64/l2 T4-OOM cell.
- IBM AML Large, Medium GINE, DGraphFin RB30 extra architectures, and RB18 remain resource-blocked/blocked. They carry no performance metrics.
- V29-V39 are downstream analysis, contract, evaluator, or release surfaces. They do not supersede V26-V28 empirical locks.

## Compact inventory

{markdown_table(rows, compact_fields)}
"""
    (OUT / "EVIDENCE_INVENTORY.md").write_text(text, encoding="utf-8")


def main() -> None:
    rows: list[dict[str, Any]] = []
    add_rb09(rows)
    add_rb11(rows)
    add_v22(rows)
    add_v24(rows)
    add_ibm(rows)
    add_saved_output_families(rows)
    add_governance_surfaces(rows)
    write_outputs(rows)
    print(f"wrote {len(rows)} evidence rows to {rel(OUT / 'EVIDENCE_INVENTORY.csv')}")


if __name__ == "__main__":
    main()
